### ISSUE TITLE
mochaTest fails

### ISSUE THREAD

**Issue by kasongoyo** [lykmapipo/generator-mvp#25]
**Running ```grunt libsspec``` fails with error message that mochaTest.libs is undefined**;
Please do add libs as target in mochaTest configuration

**Comment by lykmapipo** [comment]
@kasongoyo 

You will need to add your libs and their specs in `libs` directory of your `cwd`. `libsspec` is just a setup task to help you get started

**Comment by kasongoyo** [comment]
The configuration of mochaTest in GruntFile does not contain libs as one of the task target. Its not about adding specs in libs or something....!

**Comment by kasongoyo** [comment]
I have fixed it in my project and my codes are running smoothly but i just added as an issue to help future users...!

**Comment by lykmapipo** [comment]
@kasongoyo 

:+1:
